# Generated by Django 5.0.3 on 2024-08-28 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_billing_address_cart_billing_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='color_name',
            field=models.CharField(default='Default Color', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='Default Product', max_length=128),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='size_name',
            field=models.CharField(default='XS', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='Default Color', max_length=30),
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('order_quantity', models.IntegerField(default=1)),
                ('category_name', models.CharField(max_length=128)),
                ('product_name', models.CharField(max_length=128)),
                ('product_price', models.FloatField(default=0.0)),
                ('size_name', models.CharField(max_length=10)),
                ('color_name', models.CharField(max_length=20)),
                ('order_ordered_date', models.DateField(blank=True, null=True)),
                ('order_ordered', models.BooleanField(default=False)),
                ('billing_address_first_name', models.CharField(max_length=100)),
                ('billing_address_last_name', models.CharField(max_length=100)),
                ('billing_address_email', models.EmailField(max_length=254)),
                ('billing_address_mobile_no', models.CharField(max_length=15)),
                ('billing_address_region', models.CharField(max_length=100)),
                ('billing_address_municipality', models.CharField(max_length=100)),
                ('billing_address_street', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('total_price', models.FloatField()),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.billingaddress')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(related_name='carts', to='store.cartorder'),
        ),
    ]
