# Generated by Django 5.0.3 on 2025-01-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_billing_address_order_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='orders',
            field=models.ManyToManyField(related_name='carts', to='store.order'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
