# Generated by Django 5.0.3 on 2025-03-09 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_cartorder_payment_status_cart_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
