# Generated by Django 5.0.3 on 2025-03-09 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cartorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
