# Generated by Django 5.0.3 on 2025-03-09 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_cartorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
